Add dotenv
JabRef/JabRef-Word-Addin pull request #32
Opened 2021-06-10 20:33 UTC by mohit038

2021-06-10 20:38 UTC, tobiasdiez requested changes
Codewise it looks good to me. Could you please add a short documentation (say in the readme) of the `env` file, and which keys/environment variables are supported.

2021-06-10 20:38 UTC, tobiasdiez commented on src/Utils/apolloClient.ts
> +  uri: process.env.API_HOST,
I think it would be good to still fall-back to the heroku url in case the developer doesn't provide something in the env file.

2021-06-10 22:52 UTC, mohit038 commented
I think we can skip the `PORT` for now. Because  If we change the port, we also have to change the dir locations for all of these files in the manifest.


`<SourceLocation DefaultValue="https://localhost:3000/taskpane.html"/>
        <bt:Image id="Icon.16x16" DefaultValue="https://localhost:3000/assets/jabref.svg.png"/>
        <bt:Image id="Icon.32x32" DefaultValue="https://localhost:3000/assets/jabref.svg.png"/>
        <bt:Image id="Icon.80x80" DefaultValue="https://localhost:3000/assets/jabref.svg.png"/>
      </bt:Images>
      <bt:Urls>
        <bt:Url id="GetStarted.LearnMoreUrl" DefaultValue="https://go.microsoft.com/fwlink/?LinkId=276812"/>
        <bt:Url id="Commands.Url" DefaultValue="https://localhost:3000/commands.html"/>
        <bt:Url id="Taskpane.Url" DefaultValue="https://localhost:3000/taskpane.html"/>
      </bt:Urls>`

Also, the manifest file doesn't have access to `process.env.`.

2021-06-11 11:36 UTC, tobiasdiez commented
Yes, I agree it's fine to leave it hard-coded for the moment. 

It appears to me that, at some point, we need to make the manifest file configurable anyway because we need to different manifests for development (where the Word Addin server sits at localhost) and for production (where it would be at jabref.org), right? If yes, please open an issue for this so that we keep track.

2021-06-11 11:36 UTC, tobiasdiez approved these changes

2021-06-11 20:26 UTC, Siedlerchr commented
I would also add the document property where you specify the url to the word online document for testing to the env file. Otherwise it looks good

2021-06-18 14:13 UTC, mohit038 commented
> I would also add the document property where you specify the url to the word online document for testing to the env file. Otherwise it looks good
`"document": "${ENV.DOCUMENT_URL}"`
`"document": "${ENV.DOCUMENT_URL}"`

2021-06-19 10:34 UTC, Siedlerchr approved these changes

2021-06-19 10:41 UTC, tobiasdiez commented
The documentation is still missing, otherwise it looks good to me

2021-06-19 14:30 UTC, mohit038 commented
`"document": "${DOCUMENT_URL}"` doesn't actually work. I don't think it is possible to get access to  .env variables in the [configuration parameters](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#config).

2021-06-19 14:54 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
Is it possible passing it through the `--document` argument [(in optional arguments)](https://github.com/OfficeDev/Office-Addin-Scripts/blob/master/packages/office-addin-debugging/README.md#start).

2021-06-19 14:59 UTC, tobiasdiez commented
Something like the following should work
`start": "office-addin-debugging start manifest.xml - - document $DocumentUrl"` in combination with dotenv-run-script or dotenv-cli

2021-06-20 09:22 UTC, tobiasdiez approved these changes

2021-06-20 09:22 UTC, merged