add-airbnb-eslint
JabRef/JabRef-Word-Addin pull request #74
Opened 2021-06-30 20:40 UTC by mohit038

Adds eslint-Airbnb config

2021-06-30 21:07 UTC, tobiasdiez requested changes
Nice! Did you already pair-programmed with @k3KAW8Pnf7mkmdSMPHz27 ?

One small suggestion: Please also use the plugin https://www.npmjs.com/package/eslint-plugin-unused-imports to detect unused imports. Otherwise LGTM.

2021-06-30 21:37 UTC, k3KAW8Pnf7mkmdSMPHz27 requested changes
We might have to turn off more rules. @tobiasdiez, I just wanted to verify that this should be merged before fixing the ESLinter complaints in the files

2021-06-30 21:37 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on package.json
>      "eslint-plugin-react": "^7.24.0",
Oups, I think the instructions were missing the `react-hooks` dependency ([they suggest](https://www.npmjs.com/package/eslint-config-airbnb) a lower version number but 4.2 seems to work fine). Sorry about that, I have no idea why it didn't generate an error.

```suggestion
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
```

2021-07-01 06:53 UTC, tobiasdiez commented
Yes, I think it it's a good idea to merge this first and then fix the existing code later.

2021-07-01 06:54 UTC, tobiasdiez approved these changes

2021-07-01 19:00 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
I think we need to turn the "regular" un-def off as well (see [the FAQ for motivation](https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors)). Either that or put the JSX global back on (sorry)

2021-07-06 23:29 UTC, k3KAW8Pnf7mkmdSMPHz27 approved these changes
Sorry about the delay. I think it looks good! If something more pop-ups we can address it in a new PR.

2021-07-06 23:29 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on .eslintrc.json
> +  "parser": "@typescript-eslint/parser",
Perhaps also

```suggestion
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  }
```

although it doesn't seem to have caused any issues having it off?

2021-07-10 02:05 UTC, merged